apiVersion: apps/v1
kind: Deployment
metadata:
  name: PlatformOrchestration
  labels:
    app: PlatformOrchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PlatformOrchestration
  template:
    metadata:
      labels:
        app: PlatformOrchestration
    spec:
      containers:
        - name: PlatformOrchestration
          image: "username/PlatformOrchestration:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
