apiVersion: v1
kind: Service
metadata:
  name: PlatformOrchestration
  labels:
    app: PlatformOrchestration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PlatformOrchestration