apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContentPublication
  labels:
    app: ContentPublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ContentPublication
  template:
    metadata:
      labels:
        app: ContentPublication
    spec:
      containers:
        - name: ContentPublication
          image: "username/ContentPublication:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
