apiVersion: apps/v1
kind: Deployment
metadata:
  name: WriterManagement
  labels:
    app: WriterManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WriterManagement
  template:
    metadata:
      labels:
        app: WriterManagement
    spec:
      containers:
        - name: WriterManagement
          image: "username/WriterManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
