---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: WriterManagement
  labels:
    app: WriterManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WriterManagement
  template:
    metadata:
      labels:
        app: WriterManagement
    spec:
      containers:
        - name: WriterManagement
          image: username/WriterManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContentPublication
  labels:
    app: ContentPublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ContentPublication
  template:
    metadata:
      labels:
        app: ContentPublication
    spec:
      containers:
        - name: ContentPublication
          image: username/ContentPublication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SubscriptionAndPoint
  labels:
    app: SubscriptionAndPoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriptionAndPoint
  template:
    metadata:
      labels:
        app: SubscriptionAndPoint
    spec:
      containers:
        - name: SubscriptionAndPoint
          image: username/SubscriptionAndPoint:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AIServices
  labels:
    app: AIServices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AIServices
  template:
    metadata:
      labels:
        app: AIServices
    spec:
      containers:
        - name: AIServices
          image: username/AIServices:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: PlatformOrchestration
  labels:
    app: PlatformOrchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PlatformOrchestration
  template:
    metadata:
      labels:
        app: PlatformOrchestration
    spec:
      containers:
        - name: PlatformOrchestration
          image: username/PlatformOrchestration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: WriterManagement
  labels:
    app: WriterManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: WriterManagement


---


apiVersion: v1
kind: Service
metadata:
  name: ContentPublication
  labels:
    app: ContentPublication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ContentPublication


---


apiVersion: v1
kind: Service
metadata:
  name: SubscriptionAndPoint
  labels:
    app: SubscriptionAndPoint
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SubscriptionAndPoint


---


apiVersion: v1
kind: Service
metadata:
  name: AIServices
  labels:
    app: AIServices
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AIServices


---


apiVersion: v1
kind: Service
metadata:
  name: PlatformOrchestration
  labels:
    app: PlatformOrchestration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PlatformOrchestration

